name              'yum-remi-chef'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures the Remi\'s yum repository'
version           '4.2.1'
source_url        'https://github.com/sous-chefs/yum-remi-chef'
issues_url        'https://github.com/sous-chefs/yum-remi-chef/issues'
chef_version      '>= 12.15'

depends 'yum-epel'

supports 'amazon'
supports 'centos'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
